#!/usr/bin/python3

import os
import datetime

mediaPath="/home/pi/gPodder/Downloads"

def DeleteOldFilesInFolder( path, age ):
    #print("deleting, path: ", path)
    for dirpath, dirname, filenames in os.walk(path):
        for old_file in filenames:
            curpath = os.path.join(dirpath, old_file)
            file_modified = datetime.datetime.fromtimestamp(os.path.getmtime(curpath))
            if datetime.datetime.now() - file_modified > datetime.timedelta(hours=age):
                os.remove(curpath)

def CleanPodcastDir():
    DeleteOldFilesInFolder( os.path.join(mediaPath, "DetektorKino"), 24 )
    
    DeleteOldFilesInFolder( "/home/pi/podcast/DetektorKino", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/DetektorMusik", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/DetektorPolitik", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/DetektorWirtschaft", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/dradio-Wissenschaft und Bildung", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/Mahlzeit", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/Nachrichten", 1 )
    DeleteOldFilesInFolder( "/home/pi/podcast/NeuesVomKaenguru", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/Ombudsmann", 24 )
    DeleteOldFilesInFolder( "/home/pi/podcast/ScienceBusters", 24 )

CleanPodcastDir()
